/**
 * sample_data.js — Datos iniciales de demostración
 * NOTA: Las fases usan keys SIN acentos ni caracteres especiales
 * para garantizar compatibilidad con getElementById.
 * Keys válidos: Abertura | Reuniao | Analise | Comite |
 *               Apresentacao | Aprovacao | Execucao | Concluida
 */
const initialChangesData = [
  {
    id: 'CHG-DEMO-001',
    spId: 1001,
    numeroChange: 'CHG0089201',
    ritm: 'RITM0145220',
    solicitante: 'Andrés Delgado',
    pais: 'Brasil',
    businessService: 'E-Commerce & Sales',
    producto: 'Nescafé',
    descripcion: 'Optimización del proceso de checkout B2B con cálculo automático de impuestos regionales',
    engenheiro: 'Carlos Mendoza',
    horasEstimadas: 18,
    horasAprovadas: 18,
    tipoChange: 'Mejora',
    faseAtual: 'Execucao',
    statusAprovacao: 'Aprovado',
    aprovadorNome: 'Mariana Silva',
    aprovadorEmail: 'mariana.silva@nestle.com',
    analise: 'Ajuste en el módulo de cálculo de impuestos para regiones brasileñas.',
    rollback: 'Reactivar versión anterior del módulo de checkout v2.3.',
    pasosImplementacion: [
      { fase: '1. Análisis Técnico', accion: 'Revisión de reglas de negocio fiscales', horas: 4, fechaTentativa: '2026-08-05' },
      { fase: '3. Desarrollo', accion: 'Implementación del módulo de cálculo', horas: 10, fechaTentativa: '2026-08-10' },
      { fase: '6. Pruebas QA', accion: 'Pruebas con escenarios fiscales reales', horas: 4, fechaTentativa: '2026-08-12' }
    ],
    d1: '2026-08-01', d2: '2026-08-03', d3: '2026-08-05', d4: '2026-08-07',
    d5: '2026-08-09', d6: '2026-08-10', d7: '2026-08-12', d8: '',
    mesAno: '2026-08',
    teamsLink: '',
    historialFases: [
      { de: '', a: 'Abertura', fecha: '2026-08-01', usuario: 'Andrés Delgado' },
      { de: 'Abertura', a: 'Execucao', fecha: '2026-08-12', usuario: 'Carlos Mendoza' }
    ],
    fechaCreacion: '2026-08-01',
    fechaCierre: '',
    ultimaModificacao: '2026-08-12T10:00:00Z',
    modificadoPor: 'Carlos Mendoza'
  },
  {
    id: 'CHG-DEMO-002',
    spId: 1002,
    numeroChange: 'CHG0089245',
    ritm: 'RITM0145300',
    solicitante: 'Camila Restrepo',
    pais: 'Mexico',
    businessService: 'Customer Experience',
    producto: 'Purina Pro Plan',
    descripcion: 'Alertas automáticas de stock bajo para prevenir quiebres en canal moderno',
    engenheiro: 'Lucía Fernández',
    horasEstimadas: 22,
    horasAprovadas: 22,
    tipoChange: 'Mejora',
    faseAtual: 'Analise',
    statusAprovacao: 'Pendente',
    aprovadorNome: 'Roberto Gómez',
    aprovadorEmail: 'roberto.gomez@nestle.com',
    analise: 'Configurar triggers en el ERP para stock mínimo por SKU y canal.',
    rollback: 'Desactivar triggers configurados en el ERP.',
    pasosImplementacion: [
      { fase: '1. Análisis Técnico', accion: 'Mapeo de SKUs y canales', horas: 6, fechaTentativa: '2026-08-06' },
      { fase: '3. Desarrollo', accion: 'Configuración de triggers en ERP', horas: 12, fechaTentativa: '2026-08-14' },
      { fase: '6. Pruebas QA', accion: 'Validación con equipo comercial', horas: 4, fechaTentativa: '2026-08-16' }
    ],
    d1: '2026-08-02', d2: '2026-08-04', d3: '2026-08-06', d4: '',
    d5: '', d6: '', d7: '', d8: '',
    mesAno: '2026-08',
    teamsLink: '',
    historialFases: [
      { de: '', a: 'Abertura', fecha: '2026-08-02', usuario: 'Camila Restrepo' },
      { de: 'Abertura', a: 'Analise', fecha: '2026-08-06', usuario: 'Lucía Fernández' }
    ],
    fechaCreacion: '2026-08-02',
    fechaCierre: '',
    ultimaModificacao: '2026-08-06T09:00:00Z',
    modificadoPor: 'Lucía Fernández'
  },
  {
    id: 'CHG-DEMO-003',
    spId: 1003,
    numeroChange: 'CHG0089290',
    ritm: 'RITM0145380',
    solicitante: 'Felipe Martins',
    pais: 'Brasil',
    businessService: 'Supply Chain',
    producto: 'KitKat',
    descripcion: 'Integración de calendario de temporadas especiales con el módulo de planificación de demanda',
    engenheiro: 'Diego Vargas',
    horasEstimadas: 28,
    horasAprovadas: 25,
    tipoChange: 'Mejora',
    faseAtual: 'Comite',
    statusAprovacao: 'Pendente',
    aprovadorNome: 'Ana Torres',
    aprovadorEmail: 'ana.torres@nestle.com',
    analise: 'Mapear el calendario de temporadas y conectar vía API con el módulo de planificación.',
    rollback: 'Desconectar la integración y volver al proceso manual de actualización.',
    pasosImplementacion: [
      { fase: '1. Análisis Técnico', accion: 'Levantamiento de APIs disponibles en el módulo', horas: 6, fechaTentativa: '2026-08-08' },
      { fase: '3. Desarrollo', accion: 'Desarrollo del conector de calendario', horas: 16, fechaTentativa: '2026-08-18' },
      { fase: '6. Pruebas QA', accion: 'Pruebas de integración', horas: 6, fechaTentativa: '2026-08-22' }
    ],
    d1: '2026-08-03', d2: '2026-08-05', d3: '2026-08-08', d4: '',
    d5: '', d6: '', d7: '', d8: '',
    mesAno: '2026-08',
    teamsLink: '',
    historialFases: [
      { de: '', a: 'Abertura', fecha: '2026-08-03', usuario: 'Felipe Martins' },
      { de: 'Abertura', a: 'Comite', fecha: '2026-08-08', usuario: 'Diego Vargas' }
    ],
    fechaCreacion: '2026-08-03',
    fechaCierre: '',
    ultimaModificacao: '2026-08-08T11:00:00Z',
    modificadoPor: 'Diego Vargas'
  },
  {
    id: 'CHG-DEMO-004',
    spId: 1004,
    numeroChange: 'CHG0089310',
    ritm: 'RITM0145410',
    solicitante: 'Sandra López',
    pais: 'Colombia',
    businessService: 'Retail & Shopper',
    producto: 'Maggi',
    descripcion: 'Dashboard de seguimiento de activaciones en punto de venta con actualización diaria automática',
    engenheiro: 'Marcos Silva',
    horasEstimadas: 15,
    horasAprovadas: 15,
    tipoChange: 'Mejora',
    faseAtual: 'Concluida',
    statusAprovacao: 'Aprovado',
    aprovadorNome: 'Patricia Rojas',
    aprovadorEmail: 'patricia.rojas@nestle.com',
    analise: 'Construir un panel Power BI conectado con datos de activaciones del POS.',
    rollback: 'Desactivar el reporte automático y mantener el proceso manual.',
    pasosImplementacion: [
      { fase: '1. Análisis Técnico', accion: 'Definición de fuente de datos POS', horas: 3, fechaTentativa: '2026-07-10' },
      { fase: '3. Desarrollo', accion: 'Construcción del dashboard Power BI', horas: 9, fechaTentativa: '2026-07-18' },
      { fase: '6. Pruebas QA', accion: 'Validación con el equipo comercial', horas: 3, fechaTentativa: '2026-07-22' }
    ],
    d1: '2026-07-05', d2: '2026-07-08', d3: '2026-07-10', d4: '2026-07-13',
    d5: '2026-07-16', d6: '2026-07-18', d7: '2026-07-22', d8: '2026-07-28',
    mesAno: '2026-07',
    teamsLink: '',
    historialFases: [
      { de: '', a: 'Abertura', fecha: '2026-07-05', usuario: 'Sandra López' },
      { de: 'Abertura', a: 'Concluida', fecha: '2026-07-28', usuario: 'Marcos Silva' }
    ],
    fechaCreacion: '2026-07-05',
    fechaCierre: '2026-07-28',
    ultimaModificacao: '2026-07-28T15:00:00Z',
    modificadoPor: 'Marcos Silva'
  },
  {
    id: 'CHG-DEMO-005',
    spId: 1005,
    numeroChange: 'CHG0089355',
    ritm: 'RITM0145445',
    solicitante: 'Rodrigo Campos',
    pais: 'Argentina',
    businessService: 'Digital & Marketing',
    producto: 'Milo',
    descripcion: 'Automatización del reporte semanal de ventas digitales para el equipo de marketing',
    engenheiro: 'Valentina Cruz',
    horasEstimadas: 12,
    horasAprovadas: 12,
    tipoChange: 'Mejora',
    faseAtual: 'Aprovacao',
    statusAprovacao: 'Pendente',
    aprovadorNome: 'Gustavo Méndez',
    aprovadorEmail: 'gustavo.mendez@nestle.com',
    analise: 'Crear script Python que extrae datos del CRM y genera el reporte automáticamente cada lunes.',
    rollback: 'Desactivar el cron job del script y volver al reporte manual.',
    pasosImplementacion: [
      { fase: '1. Análisis Técnico', accion: 'Análisis de APIs del CRM disponibles', horas: 2, fechaTentativa: '2026-08-09' },
      { fase: '3. Desarrollo', accion: 'Desarrollo del script Python de extracción', horas: 7, fechaTentativa: '2026-08-13' },
      { fase: '6. Pruebas QA', accion: 'Validación de datos con equipo de marketing', horas: 3, fechaTentativa: '2026-08-15' }
    ],
    d1: '2026-08-06', d2: '2026-08-08', d3: '2026-08-09', d4: '2026-08-11',
    d5: '2026-08-13', d6: '', d7: '', d8: '',
    mesAno: '2026-08',
    teamsLink: '',
    historialFases: [
      { de: '', a: 'Abertura', fecha: '2026-08-06', usuario: 'Rodrigo Campos' },
      { de: 'Abertura', a: 'Aprovacao', fecha: '2026-08-13', usuario: 'Valentina Cruz' }
    ],
    fechaCreacion: '2026-08-06',
    fechaCierre: '',
    ultimaModificacao: '2026-08-13T14:00:00Z',
    modificadoPor: 'Valentina Cruz'
  },
  {
    id: 'CHG-DEMO-006',
    spId: 1006,
    numeroChange: 'CHG0089401',
    ritm: 'RITM0145500',
    solicitante: 'Isabel Fernández',
    pais: 'Chile',
    businessService: 'Finance & Operations',
    producto: 'La Lechera',
    descripcion: 'Corrección en el cálculo de bonificaciones por volumen para distribuidores afiliados',
    engenheiro: 'Tomás Herrera',
    horasEstimadas: 8,
    horasAprovadas: 8,
    tipoChange: 'Mejora',
    faseAtual: 'Reuniao',
    statusAprovacao: 'Pendente',
    aprovadorNome: 'Carmen Vidal',
    aprovadorEmail: 'carmen.vidal@nestle.com',
    analise: 'Revisar fórmulas de bonificación y ajustar parámetros en el sistema de facturación.',
    rollback: 'Revertir parámetros a valores anteriores en el sistema de facturación.',
    pasosImplementacion: [
      { fase: '1. Análisis Técnico', accion: 'Revisión de fórmulas actuales', horas: 2, fechaTentativa: '2026-08-11' },
      { fase: '3. Desarrollo', accion: 'Ajuste de parámetros en el sistema', horas: 4, fechaTentativa: '2026-08-13' },
      { fase: '6. Pruebas QA', accion: 'Validación con equipo de finanzas', horas: 2, fechaTentativa: '2026-08-14' }
    ],
    d1: '2026-08-10', d2: '', d3: '', d4: '',
    d5: '', d6: '', d7: '', d8: '',
    mesAno: '2026-08',
    teamsLink: '',
    historialFases: [
      { de: '', a: 'Abertura', fecha: '2026-08-10', usuario: 'Isabel Fernández' },
      { de: 'Abertura', a: 'Reuniao', fecha: '2026-08-11', usuario: 'Tomás Herrera' }
    ],
    fechaCreacion: '2026-08-10',
    fechaCierre: '',
    ultimaModificacao: '2026-08-11T08:00:00Z',
    modificadoPor: 'Tomás Herrera'
  },
  {
    id: 'CHG-DEMO-007',
    spId: 1007,
    numeroChange: 'CHG0089450',
    ritm: 'RITM0145550',
    solicitante: 'Rafael Souza',
    pais: 'Brasil',
    businessService: 'E-Commerce & Sales',
    producto: 'Nespresso',
    descripcion: 'Actualización del catálogo de cápsulas con precios dinámicos y disponibilidad en tiempo real',
    engenheiro: 'Bianca Oliveira',
    horasEstimadas: 30,
    horasAprovadas: 30,
    tipoChange: 'Mejora',
    faseAtual: 'Abertura',
    statusAprovacao: 'Pendente',
    aprovadorNome: 'Paulo Carvalho',
    aprovadorEmail: 'paulo.carvalho@nestle.com',
    analise: 'Conectar el catálogo del ecommerce con el sistema de pricing en tiempo real.',
    rollback: 'Revertir a catálogo estático con precios manuales.',
    pasosImplementacion: [
      { fase: '1. Análisis Técnico', accion: 'Análisis de APIs de pricing disponibles', horas: 5, fechaTentativa: '2026-08-14' },
      { fase: '3. Desarrollo', accion: 'Integración API catálogo ↔ pricing', horas: 20, fechaTentativa: '2026-08-25' },
      { fase: '6. Pruebas QA', accion: 'Pruebas de carga y consistencia de precios', horas: 5, fechaTentativa: '2026-08-28' }
    ],
    d1: '2026-08-13', d2: '', d3: '', d4: '',
    d5: '', d6: '', d7: '', d8: '',
    mesAno: '2026-08',
    teamsLink: '',
    historialFases: [
      { de: '', a: 'Abertura', fecha: '2026-08-13', usuario: 'Rafael Souza' }
    ],
    fechaCreacion: '2026-08-13',
    fechaCierre: '',
    ultimaModificacao: '2026-08-13T16:00:00Z',
    modificadoPor: 'Rafael Souza'
  }
];
