/**
 * Datos iniciales preconfigurados para demostración y arranque inmediato
 * Enfoque exclusivo en Small Enhancements (<= 30 horas) para el equipo de mejoras continuas
 */
const initialChangesData = [
    {
        id: "CHG-2026-001",
        spId: 1,
        numeroChange: "CHG0089201",
        ritm: "RITM0145220",
        solicitante: "Andrés Delgado",
        businessService: "E-Commerce & Digital Sales",
        producto: "Nescafé E-Commerce",
        descripcion: "Optimización del checkout B2B y cálculo automático de impuestos por región",
        mesAno: "2026-08",
        engenheiro: "Carlos Mendoza",
        horasEstimadas: 18,
        horasAprovadas: 18,
        tipoChange: "SMALL ENHANCEMENT",
        faseAtual: "Execução",
        analise: "Se requiere ajustar la API de cálculo de impuestos y actualizar el webhook de facturación en Magento/SAP.",
        pasosImplementacion: [
            { fase: "1. Análisis Técnico", accion: "Revisión de arquitectura y mapeo de impuestos fiscales", horas: 3, fechaTentativa: "2026-08-06" },
            { fase: "3. Desarrollo Backend", accion: "Modificación de endpoints de taxes", horas: 8, fechaTentativa: "2026-08-10" },
            { fase: "6. Pruebas QA", accion: "Ejecución de escenarios de prueba con órdenes", horas: 4, fechaTentativa: "2026-08-12" },
            { fase: "8. Despliegue", accion: "Pase a producción en ventana", horas: 3, fechaTentativa: "2026-08-15" }
        ],
        oQueFazer: "1. Modificar endpoints de taxes.\n2. Pruebas unitarias en QA.\n3. Despliegue con ventana de mantenimiento.",
        rollback: "Restaurar versión anterior de la API v2.4.1 desde el pipeline de GitLab.",
        aprovadorNome: "Mariana Silva",
        aprovadorEmail: "mariana.silva@nestle.com",
        statusAprovacao: "Aprovado",
        d1: "2026-08-02",
        d2: "2026-08-04",
        d3: "2026-08-06",
        d4: "2026-08-08",
        d5: "2026-08-09",
        d6: "2026-08-11",
        d7: "2026-08-13",
        d8: "",
        ultimaModificacao: "2026-08-14T08:30:00.000Z",
        modificadoPor: "Carlos Mendoza"
    },
    {
        id: "CHG-2026-002",
        spId: 2,
        numeroChange: "CHG0089205",
        ritm: "RITM0145241",
        solicitante: "Camila Restrepo",
        businessService: "Customer Experience & CRM",
        producto: "Purina Pro Plan Direct",
        descripcion: "Alertas automáticas de inventario y notificación de reposición a clientes",
        mesAno: "2026-08",
        engenheiro: "Lucía Fernández",
        horasEstimadas: 28,
        horasAprovadas: 28,
        tipoChange: "SMALL ENHANCEMENT",
        faseAtual: "Comitê",
        analise: "Ajuste en microservicio de notificaciones y plantilla de correo responsiva.",
        pasosImplementacion: [
            { fase: "1. Análisis Técnico", accion: "Definición de umbrales de stock", horas: 4, fechaTentativa: "2026-08-10" },
            { fase: "3. Desarrollo Backend", accion: "Trigger en base de datos y cola Kafka", horas: 14, fechaTentativa: "2026-08-18" },
            { fase: "6. Pruebas QA", accion: "Pruebas de envío masivo", horas: 6, fechaTentativa: "2026-08-22" },
            { fase: "8. Despliegue", accion: "Activación en producción", horas: 4, fechaTentativa: "2026-08-25" }
        ],
        oQueFazer: "1. Crear jobs de stock.\n2. Conector con servicio de email.",
        rollback: "Desactivar flag de notificaciones en el config server.",
        aprovadorNome: "Roberto Gómez",
        aprovadorEmail: "roberto.gomez@nestle.com",
        statusAprovacao: "Pendente",
        d1: "2026-08-05",
        d2: "2026-08-07",
        d3: "2026-08-10",
        d4: "2026-08-12",
        d5: "",
        d6: "",
        d7: "",
        d8: "",
        ultimaModificacao: "2026-08-13T14:15:00.000Z",
        modificadoPor: "Lucía Fernández"
    },
    {
        id: "CHG-2026-003",
        spId: 3,
        numeroChange: "CHG0089210",
        ritm: "RITM0145280",
        solicitante: "Diego Morales",
        businessService: "Marketing & Gamification",
        producto: "KitKat Club Digital",
        descripcion: "Actualización de banner dinámico y gamificación para campaña de verano",
        mesAno: "2026-08",
        engenheiro: "David Morales",
        horasEstimadas: 12,
        horasAprovadas: 12,
        tipoChange: "SMALL ENHANCEMENT",
        faseAtual: "Concluída",
        analise: "Ajuste de componentes visuales en React y sincronización con tabla de premios en Firebase.",
        pasosImplementacion: [
            { fase: "2. Diseño UI", accion: "Adaptación de componentes en React", horas: 4, fechaTentativa: "2026-08-03" },
            { fase: "3. Desarrollo Backend", accion: "Integración de cupones", horas: 5, fechaTentativa: "2026-08-05" },
            { fase: "8. Despliegue", accion: "Publicación en vivo", horas: 3, fechaTentativa: "2026-08-08" }
        ],
        oQueFazer: "1. Subir assets gráficos.\n2. Probar cupones.\n3. Publicar.",
        rollback: "Revertir a versión v1.8.0 del frontend.",
        aprovadorNome: "Valeria Torres",
        aprovadorEmail: "valeria.torres@nestle.com",
        statusAprovacao: "Aprovado",
        d1: "2026-08-01",
        d2: "2026-08-02",
        d3: "2026-08-03",
        d4: "2026-08-04",
        d5: "2026-08-05",
        d6: "2026-08-06",
        d7: "2026-08-07",
        d8: "2026-08-08",
        ultimaModificacao: "2026-08-08T18:00:00.000Z",
        modificadoPor: "David Morales"
    },
    {
        id: "CHG-2026-004",
        spId: 4,
        numeroChange: "CHG0089218",
        ritm: "RITM0145312",
        solicitante: "Andrés Delgado",
        businessService: "Supply Chain & Orders",
        producto: "Maggi Food Service",
        descripcion: "Reporte automático de pedidos mayoristas en formato PDF y envío por correo",
        mesAno: "2026-08",
        engenheiro: "Sofía Rivas",
        horasEstimadas: 24,
        horasAprovadas: 24,
        tipoChange: "SMALL ENHANCEMENT",
        faseAtual: "Aprovação",
        analise: "Generación de microservicio de plantillas PDF con Node.js y trigger en base de datos de órdenes.",
        pasosImplementacion: [
            { fase: "1. Análisis Técnico", accion: "Diseño y renderizado de template HTML a PDF", horas: 8, fechaTentativa: "2026-08-08" },
            { fase: "3. Desarrollo Backend", accion: "Integración con cola SendGrid", horas: 10, fechaTentativa: "2026-08-11" },
            { fase: "6. Pruebas QA", accion: "Pruebas de carga", horas: 6, fechaTentativa: "2026-08-14" }
        ],
        oQueFazer: "1. Crear template HTML a PDF.\n2. Configurar SendGrid.\n3. Pruebas.",
        rollback: "Regresar al envío de resumen en texto plano.",
        aprovadorNome: "Alejandro Castro",
        aprovadorEmail: "alejandro.castro@nestle.com",
        statusAprovacao: "Aprovado",
        d1: "2026-08-03",
        d2: "2026-08-05",
        d3: "2026-08-08",
        d4: "2026-08-10",
        d5: "2026-08-11",
        d6: "2026-08-13",
        d7: "",
        d8: "",
        ultimaModificacao: "2026-08-13T16:45:00.000Z",
        modificadoPor: "Sofía Rivas"
    },
    {
        id: "CHG-2026-005",
        spId: 5,
        numeroChange: "CHG0089225",
        ritm: "RITM0145350",
        solicitante: "Mariana Silva",
        businessService: "Mobile Apps & Consumers",
        producto: "La Lechera Culinary App",
        descripcion: "Filtro avanzado de recetas por alérgenos y tiempo de preparación",
        mesAno: "2026-08",
        engenheiro: "Carlos Mendoza",
        horasEstimadas: 16,
        horasAprovadas: 16,
        tipoChange: "SMALL ENHANCEMENT",
        faseAtual: "Análise",
        analise: "Indexar ingredientes y tags de alérgenos en Elasticsearch para búsqueda instantánea.",
        pasosImplementacion: [
            { fase: "1. Análisis Técnico", accion: "Mapeo de taxonomía en base de datos", horas: 4, fechaTentativa: "2026-08-12" },
            { fase: "3. Desarrollo Backend", accion: "Creación de índices Elasticsearch", horas: 6, fechaTentativa: "2026-08-15" },
            { fase: "4. Desarrollo Frontend", accion: "Componentes móviles en React Native", horas: 6, fechaTentativa: "2026-08-18" }
        ],
        oQueFazer: "1. Mapear taxonomía.\n2. Reindexar.\n3. Integrar UI.",
        rollback: "Deshabilitar sección de filtros en app móvil.",
        aprovadorNome: "Mariana Silva",
        aprovadorEmail: "mariana.silva@nestle.com",
        statusAprovacao: "Pendente",
        d1: "2026-08-08",
        d2: "2026-08-10",
        d3: "2026-08-12",
        d4: "",
        d5: "",
        d6: "",
        d7: "",
        d8: "",
        ultimaModificacao: "2026-08-12T11:00:00.000Z",
        modificadoPor: "Carlos Mendoza"
    },
    {
        id: "CHG-2026-006",
        spId: 6,
        numeroChange: "CHG0089230",
        ritm: "RITM0145399",
        solicitante: "Javier Ortega",
        businessService: "B2B Solutions",
        producto: "Nespresso Professional",
        descripcion: "Ajuste de validación de contratos y límite de crédito B2B",
        mesAno: "2026-08",
        engenheiro: "Elena Navarro",
        horasEstimadas: 30,
        horasAprovadas: 30,
        tipoChange: "SMALL ENHANCEMENT",
        faseAtual: "Abertura",
        analise: "Límite máximo permitido de 30 horas. Validación en checkout B2B con SAP.",
        pasosImplementacion: [
            { fase: "1. Análisis Técnico", accion: "Revisión de contratos y reglas SAP", horas: 6, fechaTentativa: "2026-08-15" },
            { fase: "3. Desarrollo Backend", accion: "Endpoints de validación crediticia", horas: 16, fechaTentativa: "2026-08-22" },
            { fase: "6. Pruebas QA", accion: "Pruebas integrales", horas: 8, fechaTentativa: "2026-08-28" }
        ],
        oQueFazer: "1. Conectar API SAP.\n2. Validar reglas de crédito.",
        rollback: "Revertir a validación manual.",
        aprovadorNome: "Javier Ortega",
        aprovadorEmail: "javier.ortega@nestle.com",
        statusAprovacao: "Pendente",
        d1: "2026-08-12",
        d2: "",
        d3: "",
        d4: "",
        d5: "",
        d6: "",
        d7: "",
        d8: "",
        ultimaModificacao: "2026-08-12T09:20:00.000Z",
        modificadoPor: "Elena Navarro"
    }
];
